### PR TITLE
Fixed: Posting empty comments

### LINKED ISSUE #740: Validation is required for comments
### Description

An empty comment with just a blank space is accepted.

### Steps to reproduce

Enter a comment with just spaces and click post.

### Screenshots

image

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by VijayalakshmiGanesh**
This PR fixes #740.

1. Empty comments can't be posted anymore.
2. Comments max length is set to 150 characters.

### CODE REVIEW

File: src/components/Post/CommentBox.jsx [hunk 1]
```diff
@@ -60,7 +61,7 @@ const CommentBox = ({
 
           <IconButton
             className="post__button"
-            disabled={!comment}
+            disabled={!comment || comment.trim().length < 1}
```
Comment (narayan954) [inline src/components/Post/CommentBox.jsx]: won't `comment.trim().length < 1` work the same as `!comment`? I think we wont need that

**Review by narayan954 — APPROVED** [review]
looks good to me!

File: src/components/Post/CommentBox.jsx (hunk 1 above)
Comment (VijayalakshmiGanesh) [reply src/components/Post/CommentBox.jsx]: `!comment` checks if its not null, undefined. But `comment.trim().length < 1` check if the comment is empty or contains only white spaces. 

But you are right. In this LOC, `!comment` seems redundant.
